CREATE TABLE IF NOT EXISTS Event (
        eid INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255),
        location VARCHAR(255),
        month VARCHAR(50)
    );
CREATE TABLE IF NOT EXISTS Participant (
        pid INT AUTO_INCREMENT PRIMARY KEY,
        fname VARCHAR(255),
        lname VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS Model (
        mid INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255)
    );
CREATE TABLE IF NOT EXISTS Medal (
        Category VARCHAR(255),
        Year YEAR,
        Award VARCHAR(50),
        mid INT,
        pid INT,
        eid INT,
        FOREIGN KEY (eid) REFERENCES Event(eid),
        FOREIGN KEY (pid) REFERENCES Participant(pid),
        FOREIGN KEY (mid) REFERENCES Model(mid),
        PRIMARY KEY (mid, pid, eid)
    );
INSERT INTO Event (eid, name, location, month) VALUES (1, "Adepticon Golden Demon", "Schaumburg IL USA", "March");
INSERT INTO Event (eid, name, location, month) VALUES (2, "Atlanta Military Figure Society Show", "Atlanta GA USA", "February");
INSERT INTO Event (eid, name, location, month) VALUES (3, "Coulee Con The DAWG Show Miniature Painting Contest", "La Crosse WI USA", "August");
INSERT INTO Event (eid, name, location, month) VALUES (4, "Dragon Fall Contest Info", "Lake Geneva WI USA", "October");
INSERT INTO Event (eid, name, location, month) VALUES (5, "Euro Miniature Expo Euro Militaire", "Folkstone UK USA", "January");
INSERT INTO Event (eid, name, location, month) VALUES (6, "Euro Model Expo", "Berlin Germany", "Various Dates");
INSERT INTO Event (eid, name, location, month) VALUES (7, "Euroma", "Rome Italy", "Various Dates");
INSERT INTO Event (eid, name, location, month) VALUES (8, "FreakWars Madrid Miniature Painting Competition", "Madrid Spain", "September");
INSERT INTO Event (eid, name, location, month) VALUES (9, "Gen Con Hobby Class Events", "Indianapolis IN USA", "August");
INSERT INTO Event (eid, name, location, month) VALUES (10, "Hammerhead Painting Competition", "Newark UK", "March");
INSERT INTO Event (eid, name, location, month) VALUES (11, "Historicon Painting Contest", "Lancaster PA USA", "July");
INSERT INTO Event (eid, name, location, month) VALUES (12, "Houston Miniature Arts Painting Competition", "Houston TX USA", "September");
INSERT INTO Event (eid, name, location, month) VALUES (13, "IPMS Shows", "Chicago IL USA", "Various Dates");
INSERT INTO Event (eid, name, location, month) VALUES (14, "KublaCon Miniature Painting Contest", "San Francisco CA USA", "May");
INSERT INTO Event (eid, name, location, month) VALUES (15, "Las Vegas Open Miniature Contests", "Las Vegas NV USA", "January");
INSERT INTO Event (eid, name, location, month) VALUES (16, "Miniature Collectors of America Shows", "Boston MA USA", "Various Dates");
INSERT INTO Event (eid, name, location, month) VALUES (17, "Model Expo Italy", "Verona Italy", "March");
INSERT INTO Event (eid, name, location, month) VALUES (18, "Moson Show", "Mosonmagyaróvár Hungary", "April");
INSERT INTO Event (eid, name, location, month) VALUES (19, "Nova Open Information", "Arlington VA USA", "August-September");
INSERT INTO Event (eid, name, location, month) VALUES (20, "ORCCON Painting Contest", "Los Angeles CA USA", "February");
INSERT INTO Event (eid, name, location, month) VALUES (21, "Origins Painting Contest", "Columbus OH USA", "June");
INSERT INTO Event (eid, name, location, month) VALUES (22, "Polar Vortex Miniature Painting and Modeling Competition", "Lisle IL USA", "February");
INSERT INTO Event (eid, name, location, month) VALUES (23, "ReaperCon Painting Contest", "Denton TX USA", "August-September");
INSERT INTO Event (eid, name, location, month) VALUES (24, "SOLDAT de PLOM Painting Contest", "Girona Spain", "October");
INSERT INTO Event (eid, name, location, month) VALUES (25, "TantrumCon Miniature Painting Contest", "Charlotte NC USA", "January");
INSERT INTO Event (eid, name, location, month) VALUES (26, "The Long Island Miniatures Model Show", "New York NY USA", "November");
INSERT INTO Event (eid, name, location, month) VALUES (27, "The Mug and Meeple Painting Competition 2023", "London UK", "August");
INSERT INTO Event (eid, name, location, month) VALUES (28, "Warfaire Weekend Painting Contest", "St. Louis MO USA", "November");
INSERT INTO Event (eid, name, location, month) VALUES (29, "Warhammer Fest Europe", "Manchester Central UK", "April");
INSERT INTO Event (eid, name, location, month) VALUES (30, "World Model Expo 2022", "Veldhoven The Netherlands", "Various Dates");
INSERT INTO Event (eid, name, location, month) VALUES (31, "OctoPainting", "Paris France", "February");
INSERT INTO Event (eid, name, location, month) VALUES (32, "Big Child Painting Royale", "Online", "March");
INSERT INTO Event (eid, name, location, month) VALUES (33, "Eavier Metal", "Online", "April");
INSERT INTO Event (eid, name, location, month) VALUES (34, "Armies on Parade", "San Diego CA USA", "June");
INSERT INTO Event (eid, name, location, month) VALUES (35, "Crystal Brush", "Chicago IL USA", "July");
INSERT INTO Event (eid, name, location, month) VALUES (36, "Euro Militaire", "London UK", "August");
INSERT INTO Event (eid, name, location, month) VALUES (37, "Everchosen", "Toronto Canada", "September");
INSERT INTO Event (eid, name, location, month) VALUES (38, "Golden Demon Classic", "Manchester UK", "October");
INSERT INTO Event (eid, name, location, month) VALUES (39, "IronSkull", "New York NY USA", "April");
INSERT INTO Event (eid, name, location, month) VALUES (40, "Miniature Painting Open", "Orlando FL USA", "June");
INSERT INTO Event (eid, name, location, month) VALUES (41, "Minipainting Contest", "Online", "May");
INSERT INTO Event (eid, name, location, month) VALUES (42, "P3 Grandmaster", "Dallas TX USA", "March");
INSERT INTO Event (eid, name, location, month) VALUES (43, "Polar Vortex’s Miniature Painting & Modeling Competition", "Chicago IL USA", "May");
INSERT INTO Event (eid, name, location, month) VALUES (44, "Resin Beast", "Las Vegas NV USA", "July");
INSERT INTO Event (eid, name, location, month) VALUES (45, "Sol Showdown", "Phoenix AZ USA", "September");
INSERT INTO Event (eid, name, location, month) VALUES (46, "The Warhammer Community Painting Competition", "Online", "October");
INSERT INTO Event (eid, name, location, month) VALUES (47, "Verbania Model Show", "Milan Italy", "March");
INSERT INTO Event (eid, name, location, month) VALUES (48, "Wyrd Painting Contests", "San Francisco CA USA", "May");
INSERT INTO Event (eid, name, location, month) VALUES (49, "Resin Beast", "Los Angeles CA USA", "June");
INSERT INTO Event (eid, name, location, month) VALUES (50, "Path of the Worthy", "Boston MA USA", "April");
INSERT INTO Event (eid, name, location, month) VALUES (51, "Reaper Miniatures Painting Contests", "Online", "August");
INSERT INTO Event (eid, name, location, month) VALUES (52, "Chicago AdeptiCon", "Schaumburg IL USA", "March");
INSERT INTO Event (eid, name, location, month) VALUES (53, "RESIN BEAST Competition", "Las Vegas NV USA", "July");
INSERT INTO Event (eid, name, location, month) VALUES (54, "MSP Open", "Denton TX USA", "August");
INSERT INTO Event (eid, name, location, month) VALUES (55, "Nova Open", "Washington D.C. USA", "September");
INSERT INTO Event (eid, name, location, month) VALUES (56, "IPMS National Convention", "San Marcos TX USA", "July");
INSERT INTO Event (eid, name, location, month) VALUES (57, "LVO (Las Vegas Open)", "Las Vegas NV USA", "February");
INSERT INTO Event (eid, name, location, month) VALUES (58, "World Model Expo", "Eindhoven Netherlands", "June");
INSERT INTO Event (eid, name, location, month) VALUES (59, "Salute", "London UK", "March");
INSERT INTO Event (eid, name, location, month) VALUES (60, "BrisCon", "Brisbane Australia", "November");
INSERT INTO Participant (fname, lname) VALUES ("Neil", "Hollis");
INSERT INTO Model (name) VALUES ("Exodite");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2024", "Gold", 1, 1, 52);
INSERT INTO Participant (fname, lname) VALUES ("Lee", "Jeonghoon");
INSERT INTO Model (name) VALUES ("Illuminor Szeras");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2024", "Silver", 2, 2, 52);
INSERT INTO Participant (fname, lname) VALUES ("Kwan", "Ho Kim");
INSERT INTO Model (name) VALUES ("High Marshal Helbrecht");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2024", "Bronze", 3, 3, 52);
INSERT INTO Model (name) VALUES ("Black Templars");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Unit or Kill Team", "2024", "Gold", 3, 3, 52);
INSERT INTO Participant (fname, lname) VALUES ("Sam", "Lenz");
INSERT INTO Model (name) VALUES ("Beast Snagga Boyz");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Unit or Kill Team", "2024", "Silver", 4, 4, 52);
INSERT INTO Model (name) VALUES ("Ultramarines");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Unit or Kill Team", "2024", "Bronze", 2, 2, 52);
INSERT INTO Participant (fname, lname) VALUES ("Julien", "Charbonneau-Gravel");
INSERT INTO Model (name) VALUES ("Vashtorr the Arkifane");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model Or Vehicle", "2024", "Gold", 5, 5, 52);
INSERT INTO Participant (fname, lname) VALUES ("Jesus", "Valera Navarro");
INSERT INTO Model (name) VALUES ("Leman Russ Battle Tank");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model Or Vehicle", "2024", "Silver", 6, 6, 52);
INSERT INTO Participant (fname, lname) VALUES ("Ellis", "Kaye");
INSERT INTO Model (name) VALUES ("Myphitic Blight-hauler");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model Or Vehicle", "2024", "Bronze", 7, 7, 52);
INSERT INTO Participant (fname, lname) VALUES ("David", "Ugolini");
INSERT INTO Model (name) VALUES ("Lord of Hubris");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Single Miniature", "2024", "Gold", 8, 8, 52);
INSERT INTO Participant (fname, lname) VALUES ("Dimosthenis", "Xylas");
INSERT INTO Model (name) VALUES ("Radukar, The Beast");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Single Miniature", "2024", "Silver", 9, 9, 52);
INSERT INTO Participant (fname, lname) VALUES ("Andy", "Wardle");
INSERT INTO Model (name) VALUES ("Freeguild Marshal");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Single Miniature", "2024", "Bronze", 10, 10, 52);
INSERT INTO Participant (fname, lname) VALUES ("Michael", "Thomas");
INSERT INTO Model (name) VALUES ("Saurus Warriors");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Unit or Warcry Warband", "2024", "Gold", 11, 11, 52);
INSERT INTO Participant (fname, lname) VALUES ("Nikolas", "Rubens Mortensen");
INSERT INTO Model (name) VALUES ("Maggotkin of Nurgle");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Unit or Warcry Warband", "2024", "Silver", 12, 12, 52);
INSERT INTO Participant (fname, lname) VALUES ("Jon", "Ninas");
INSERT INTO Model (name) VALUES ("Cities of Sigmar");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Unit or Warcry Warband", "2024", "Bronze", 13, 13, 52);
INSERT INTO Participant (fname, lname) VALUES ("Rubén", "Martínez");
INSERT INTO Model (name) VALUES ("Alarielle the Everqueen");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Large Model or War Machine", "2024", "Gold", 14, 14, 52);
INSERT INTO Participant (fname, lname) VALUES ("Liam", "Hopkins");
INSERT INTO Model (name) VALUES ("Orpheon Katakros");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Large Model or War Machine", "2024", "Silver", 15, 15, 52);
INSERT INTO Participant (fname, lname) VALUES ("Kelsey", "Graham");
INSERT INTO Model (name) VALUES ("Vengorian Lord");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Age of Sigmar: Large Model or War Machine", "2024", "Bronze", 16, 16, 52);
INSERT INTO Participant (fname, lname) VALUES ("Marco", "Frisoni");
INSERT INTO Model (name) VALUES ("Thranduil");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2024", "Gold", 17, 17, 52);
INSERT INTO Participant (fname, lname) VALUES ("Kamil", "Kozyra");
INSERT INTO Model (name) VALUES ("Easterling");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2024", "Silver", 18, 18, 52);
INSERT INTO Model (name) VALUES ("Goblin");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2024", "Bronze", 1, 1, 52);
INSERT INTO Model (name) VALUES ("Perturabo");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: The Horus Heresy", "2024", "Gold", 8, 8, 52);
INSERT INTO Participant (fname, lname) VALUES ("Matthew", "Cantor");
INSERT INTO Model (name) VALUES ("Night Lord");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: The Horus Heresy", "2024", "Silver", 19, 19, 52);
INSERT INTO Participant (fname, lname) VALUES ("Aaron", "Clark");
INSERT INTO Model (name) VALUES ("Horus");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: The Horus Heresy", "2024", "Bronze", 20, 20, 52);
INSERT INTO Model (name) VALUES ("Sons of Velmorn");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Underworlds", "2024", "Gold", 8, 8, 52);
INSERT INTO Participant (fname, lname) VALUES ("Johan", "Van Beers");
INSERT INTO Model (name) VALUES ("Hedkrakka's Madmob");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Underworlds", "2024", "Silver", 21, 21, 52);
INSERT INTO Model (name) VALUES ("Gnarlspirit");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Underworlds", "2024", "Bronze", 15, 15, 52);
INSERT INTO Participant (fname, lname) VALUES ("Wei", "Hui");
INSERT INTO Model (name) VALUES ("Goliath Gang");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Necromunda", "2024", "Gold", 22, 22, 52);
INSERT INTO Participant (fname, lname) VALUES ("Clayton", "Correia");
INSERT INTO Model (name) VALUES ("Cawdor Gang");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Necromunda", "2024", "Silver", 23, 23, 52);
INSERT INTO Participant (fname, lname) VALUES ("James", "Taro");
INSERT INTO Model (name) VALUES ("Vartijan Exo-Drille");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Necromunda", "2024", "Bronze", 24, 24, 52);
INSERT INTO Model (name) VALUES ("Bilerot Vomitflesh");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Blood Bowl", "2024", "Gold", 12, 12, 52);
INSERT INTO Participant (fname, lname) VALUES ("Bob", "Cohoon");
INSERT INTO Model (name) VALUES ("Greenfield Grasshuggers");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Blood Bowl", "2024", "Silver", 25, 25, 52);
INSERT INTO Model (name) VALUES ("Count Luthor von Drakenborg");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Blood Bowl", "2024", "Bronze", 18, 18, 52);
INSERT INTO Model (name) VALUES ("Reaver Titan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Epic Scale", "2024", "Gold", 24, 24, 52);
INSERT INTO Participant (fname, lname) VALUES ("Fletcher", "Giles");
INSERT INTO Model (name) VALUES ("Tiger Shark");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Epic Scale", "2024", "Silver", 26, 26, 52);
INSERT INTO Participant (fname, lname) VALUES ("Alexis", "L'Huillier");
INSERT INTO Model (name) VALUES ("Thunderbolt");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Epic Scale", "2024", "Bronze", 27, 27, 52);
INSERT INTO Model (name) VALUES ("Troll");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: The Old World", "2024", "Gold", 12, 12, 52);
INSERT INTO Participant (fname, lname) VALUES ("Raphael", "Boyon");
INSERT INTO Model (name) VALUES ("Bohemond");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: The Old World", "2024", "Silver", 28, 28, 52);
INSERT INTO Participant (fname, lname) VALUES ("Andrew", "Waxtel");
INSERT INTO Model (name) VALUES ("Freeguild Cavalier-Marshal");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: The Old World", "2024", "Bronze", 29, 29, 52);
INSERT INTO Participant (fname, lname) VALUES ("Alexandre", "Dos Santos");
INSERT INTO Model (name) VALUES ("The Hollow King");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Duel", "2024", "Gold", 30, 30, 52);
INSERT INTO Participant (fname, lname) VALUES ("Benjamin", "Kantor");
INSERT INTO Model (name) VALUES ("Space Hulk");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Duel", "2024", "Silver", 31, 31, 52);
INSERT INTO Model (name) VALUES ("Gimme Da Shoot");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Duel", "2024", "Bronze", 24, 24, 52);
INSERT INTO Participant (fname, lname) VALUES ("Ben", "Trentacoste");
INSERT INTO Model (name) VALUES ("Thunder Valley Greenskins");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2024", "Gold", 32, 32, 52);
INSERT INTO Participant (fname, lname) VALUES ("Xander", "Madou");
INSERT INTO Model (name) VALUES ("Eternus, Blade of The First Prince");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2024", "Silver", 33, 33, 52);
INSERT INTO Participant (fname, lname) VALUES ("Rowan", "Macdonald");
INSERT INTO Model (name) VALUES ("Merek Grimaldus");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2024", "Bronze", 34, 34, 52);
INSERT INTO Participant (fname, lname) VALUES ("Matthew", "Kennedy");
INSERT INTO Model (name) VALUES ("Skink Starseer");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2024", "Gold", 35, 35, 52);
INSERT INTO Participant (fname, lname) VALUES ("Richard", "Gray");
INSERT INTO Model (name) VALUES ("Loonboss on Giant Cave Squig");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2024", "Silver", 36, 36, 52);
INSERT INTO Participant (fname, lname) VALUES ("Jeffrey", "Harrison Bowden");
INSERT INTO Model (name) VALUES ("Jain Zar");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2024", "Bronze", 37, 37, 52);
INSERT INTO Model (name) VALUES ("Master Lazarus");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2023", "Gold", 1, 1, 52);
INSERT INTO Model (name) VALUES ("Jaghatai Khan, Primarch of The White Scars");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2023", "Silver", 30, 30, 52);
INSERT INTO Model (name) VALUES ("Rocket Grot Squig-Cycle");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2023", "Bronze", 24, 24, 52);
INSERT INTO Model (name) VALUES ("Astra Militarum");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Squad", "2023", "Gold", 12, 12, 52);
INSERT INTO Participant (fname, lname) VALUES ("Mohamed", "Aït-Mehdi");
INSERT INTO Model (name) VALUES ("Corsair Voidscarred");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Squad", "2023", "Silver", 38, 38, 52);
INSERT INTO Participant (fname, lname) VALUES ("John", "Carter");
INSERT INTO Model (name) VALUES ("Necromunda Gang");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Squad", "2023", "Bronze", 39, 39, 52);
INSERT INTO Participant (fname, lname) VALUES ("Ivan", "Bocic");
INSERT INTO Model (name) VALUES ("Knight Valiant");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Vehicle", "2023", "Gold", 40, 40, 52);
INSERT INTO Participant (fname, lname) VALUES ("Colin", "Eidenschink");
INSERT INTO Model (name) VALUES ("Penitent Engine");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Vehicle", "2023", "Silver", 41, 41, 52);
INSERT INTO Participant (fname, lname) VALUES ("Steve", "Garcia");
INSERT INTO Model (name) VALUES ("Ultramarines Leviathan Dreadnought");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Vehicle", "2023", "Bronze", 42, 42, 52);
INSERT INTO Model (name) VALUES ("Hive Tyrant");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model", "2023", "Gold", 7, 7, 52);
INSERT INTO Participant (fname, lname) VALUES ("Ian", "Stanley");
INSERT INTO Model (name) VALUES ("Unknown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model", "2023", "Silver", 43, 43, 52);
INSERT INTO Participant (fname, lname) VALUES ("Adrian", "Pech");
INSERT INTO Model (name) VALUES ("The Yncarne");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model", "2023", "Bronze", 44, 44, 52);
INSERT INTO Model (name) VALUES ("Glutos Orscollion, Lord of Gluttony");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Single Miniature", "2023", "Gold", 10, 10, 52);
INSERT INTO Participant (fname, lname) VALUES ("Todd", "Swanson");
INSERT INTO Model (name) VALUES ("Unknown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Single Miniature", "2023", "Silver", 45, 45, 52);
INSERT INTO Participant (fname, lname) VALUES ("Piotr", "Czajka");
INSERT INTO Model (name) VALUES ("Ogor Mawtribes Tyrant");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Single Miniature", "2023", "Bronze", 46, 46, 52);
INSERT INTO Model (name) VALUES ("Chosen");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Unit", "2023", "Gold", 11, 11, 52);
INSERT INTO Model (name) VALUES ("Unknown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Unit", "2023", "Silver", 41, 41, 52);
INSERT INTO Participant (fname, lname) VALUES ("John", "Margiotta");
INSERT INTO Model (name) VALUES ("Nurgle Lords");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Unit", "2023", "Bronze", 47, 47, 52);
INSERT INTO Model (name) VALUES ("Kragnos, the End of Empires");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Large Model", "2023", "Gold", 41, 41, 52);
INSERT INTO Participant (fname, lname) VALUES ("Katarzyna", "Górska");
INSERT INTO Model (name) VALUES ("Mega-Gargant");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Large Model", "2023", "Silver", 48, 48, 52);
INSERT INTO Model (name) VALUES ("Mangler Squigs");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Large Model", "2023", "Bronze", 28, 28, 52);
INSERT INTO Model (name) VALUES ("Horus vs The Emperor");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Battle Scene", "2023", "Gold", 31, 31, 52);
INSERT INTO Participant (fname, lname) VALUES ("Oscar", "Lars");
INSERT INTO Model (name) VALUES ("Unknown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Battle Scene", "2023", "Silver", 49, 49, 52);
INSERT INTO Model (name) VALUES ("Unknown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Battle Scene", "2023", "Bronze", 46, 46, 52);
INSERT INTO Participant (fname, lname) VALUES ("Sergio", "Calvo");
INSERT INTO Model (name) VALUES ("Mangler Squigs vs Bretonnain Man");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2023", "Gold", 50, 50, 52);
INSERT INTO Participant (fname, lname) VALUES ("Eric", "McCartney");
INSERT INTO Model (name) VALUES ("Drazhar vs Howling Banshee");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2023", "Silver", 51, 51, 52);
INSERT INTO Participant (fname, lname) VALUES ("Federico", "Rovida");
INSERT INTO Model (name) VALUES ("Stormdrake Guard vs Kraken-eater Mega-Gargant");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2023", "Bronze", 52, 52, 52);
INSERT INTO Model (name) VALUES ("Elrond, Master of Rivendell");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2023", "Gold", 10, 10, 52);
INSERT INTO Model (name) VALUES ("Théoden, King of Rohan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2023", "Silver", 30, 30, 52);
INSERT INTO Model (name) VALUES ("Gandalf the White and Peregrin Took");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2023", "Bronze", 27, 27, 52);
INSERT INTO Model (name) VALUES ("Astra Militarum Vulture Gunships");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Small Scale", "2023", "Gold", 41, 41, 52);
INSERT INTO Participant (fname, lname) VALUES ("Aaron", "Call");
INSERT INTO Model (name) VALUES ("Imperial Navy Arvus Lighter");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Small Scale", "2023", "Silver", 53, 53, 52);
INSERT INTO Model (name) VALUES ("Warmaster Iconoclast Heavy Battle Titan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Small Scale", "2023", "Bronze", 24, 24, 52);
INSERT INTO Participant (fname, lname) VALUES ("Evan", "Krumlauf");
INSERT INTO Model (name) VALUES ("Marneus Calgar");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2023", "Gold", 54, 54, 52);
INSERT INTO Participant (fname, lname) VALUES ("Lukas", "Anderson");
INSERT INTO Model (name) VALUES ("Breaka-boss on Mirebrute Troggoth");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2023", "Silver", 55, 55, 52);
INSERT INTO Participant (fname, lname) VALUES ("Lucas", "Franzoni");
INSERT INTO Model (name) VALUES ("Angron, Daemon Primarch of Khorne");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2023", "Bronze", 56, 56, 52);
INSERT INTO Model (name) VALUES ("Ork");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2023", "Gold", 50, 50, 52);
INSERT INTO Model (name) VALUES ("Dark Eldar Archon");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2023", "Silver", 1, 1, 52);
INSERT INTO Participant (fname, lname) VALUES ("Erik", "Swinson");
INSERT INTO Model (name) VALUES ("Imperial Fist");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2023", "Bronze", 57, 57, 52);
INSERT INTO Participant (fname, lname) VALUES ("Robin", "McLeod");
INSERT INTO Model (name) VALUES ("Kor'sarro Khan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2022", "Gold", 58, 58, 52);
INSERT INTO Model (name) VALUES ("Master Lazarus");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2022", "Silver", 42, 42, 52);
INSERT INTO Model (name) VALUES ("Eisenbrecht");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Single Miniature", "2022", "Bronze", 30, 30, 52);
INSERT INTO Model (name) VALUES ("Saint Celestine");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Squad", "2022", "Gold", 10, 10, 52);
INSERT INTO Model (name) VALUES ("Black Templars");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Squad", "2022", "Silver", 12, 12, 52);
INSERT INTO Participant (fname, lname) VALUES ("Matthew", "Avis");
INSERT INTO Model (name) VALUES ("Blood Angels");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Squad", "2022", "Bronze", 59, 59, 52);
INSERT INTO Model (name) VALUES ("Nurgle Leviathan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Vehicle", "2022", "Gold", 47, 47, 52);
INSERT INTO Participant (fname, lname) VALUES ("Will", "Hahn");
INSERT INTO Model (name) VALUES ("Morvenn Vahl");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Vehicle", "2022", "Silver", 60, 60, 52);
INSERT INTO Model (name) VALUES ("Imperial Fist Contemptor");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Vehicle", "2022", "Bronze", 27, 27, 52);
INSERT INTO Participant (fname, lname) VALUES ("James", "Cordwell");
INSERT INTO Model (name) VALUES ("Illuminor Szeras");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model", "2022", "Gold", 61, 61, 52);
INSERT INTO Participant (fname, lname) VALUES ("Martyn", "Evans");
INSERT INTO Model (name) VALUES ("Mortarion");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model", "2022", "Silver", 62, 62, 52);
INSERT INTO Model (name) VALUES ("Ghazghkull Thraka");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000: Large Model", "2022", "Bronze", 4, 4, 52);
INSERT INTO Participant (fname, lname) VALUES ("Gavin", "Garza");
INSERT INTO Model (name) VALUES ("Huachi");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Single Miniature", "2022", "Gold", 63, 63, 52);
INSERT INTO Model (name) VALUES ("Sigvald, Prince of Slaanesh");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Single Miniature", "2022", "Silver", 48, 48, 52);
INSERT INTO Model (name) VALUES ("Ghulgoch the Butcher");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Single Miniature", "2022", "Bronze", 58, 58, 52);
INSERT INTO Model (name) VALUES ("The Crimson Court");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Unit", "2022", "Gold", 58, 58, 52);
INSERT INTO Participant (fname, lname) VALUES ("Mamikon", "Khachikyan");
INSERT INTO Model (name) VALUES ("Chaos Knights");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Unit", "2022", "Silver", 64, 64, 52);
INSERT INTO Participant (fname, lname) VALUES ("Anthony", "Wang");
INSERT INTO Model (name) VALUES ("Sepulchral Guard");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Unit", "2022", "Bronze", 65, 65, 52);
INSERT INTO Model (name) VALUES ("Mindstealer Sphiranx");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Large Model", "2022", "Gold", 27, 27, 52);
INSERT INTO Participant (fname, lname) VALUES ("David", "Paz");
INSERT INTO Model (name) VALUES ("Loonboss on Mangler Squigs");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Large Model", "2022", "Silver", 66, 66, 52);
INSERT INTO Model (name) VALUES ("The Great Unclean One");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer: Age of Sigmar Large Model", "2022", "Bronze", 4, 4, 52);
INSERT INTO Model (name) VALUES ("Hallowed Ground");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Battle Scene", "2022", "Gold", 10, 10, 52);
INSERT INTO Model (name) VALUES ("And They Shall Know No Fear");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Battle Scene", "2022", "Silver", 66, 66, 52);
INSERT INTO Model (name) VALUES ("Battle for Ophelia VII, Indomitus Crusade");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Diorama & Battle Scene", "2022", "Bronze", 64, 64, 52);
INSERT INTO Model (name) VALUES ("Lion el'jonson vs Leman Russ");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2022", "Gold", 42, 42, 52);
INSERT INTO Participant (fname, lname) VALUES ("Ben", "Komets");
INSERT INTO Model (name) VALUES ("Sanguinius vs Ka'Bandha");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2022", "Silver", 67, 67, 52);
INSERT INTO Model (name) VALUES ("Loonbos vs Sylvaneth Arch Revenant");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2022", "Bronze", 10, 10, 52);
INSERT INTO Model (name) VALUES ("King of the Dead");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2022", "Gold", 61, 61, 52);
INSERT INTO Model (name) VALUES ("Aragon");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2022", "Silver", 52, 52, 52);
INSERT INTO Participant (fname, lname) VALUES ("Matt", "Cexwish");
INSERT INTO Model (name) VALUES ("Radagast the Brown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Middle-Earth", "2022", "Bronze", 68, 68, 52);
INSERT INTO Model (name) VALUES ("Imperial Navy Thunderbolt Fighter");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Small Scale", "2022", "Gold", 61, 61, 52);
INSERT INTO Model (name) VALUES ("Warmaster Titan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Small Scale", "2022", "Silver", 4, 4, 52);
INSERT INTO Model (name) VALUES ("Xiphon Interceptor");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Small Scale", "2022", "Bronze", 64, 64, 52);
INSERT INTO Participant (fname, lname) VALUES ("Luca", "Franzoni");
INSERT INTO Model (name) VALUES ("Megaboss on Maw-krusha");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2022", "Gold", 69, 69, 52);
INSERT INTO Participant (fname, lname) VALUES ("Gavin", "Grehier");
INSERT INTO Model (name) VALUES ("Unknown");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2022", "Silver", 70, 70, 52);
INSERT INTO Participant (fname, lname) VALUES ("Unawarded", "");
INSERT INTO Model (name) VALUES ("Unawarded");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Young Bloods", "2022", "Bronze", 71, 71, 52);
INSERT INTO Model (name) VALUES ("Mephiston, Lord of Death");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2022", "Gold", 57, 57, 52);
INSERT INTO Participant (fname, lname) VALUES ("Chris", "Borer");
INSERT INTO Model (name) VALUES ("World Eaters Contemptor Dreadnought");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2022", "Silver", 72, 72, 52);
INSERT INTO Model (name) VALUES ("Grot Tanks!");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("The Open Competition", "2022", "Bronze", 47, 47, 52);
INSERT INTO Participant (fname, lname) VALUES ("Tom", "Barmby");
INSERT INTO Model (name) VALUES ("Elucidian Starstriders – Voidsman");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Silver", 1, 1, 29);
INSERT INTO Participant (fname, lname) VALUES ("Kosma", "Rabiega");
INSERT INTO Model (name) VALUES ("Houston we have a problem");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Unbound", "2018", "Bronze", 2, 2, 29);
INSERT INTO Participant (fname, lname) VALUES ("Chesnel", "Vivien");
INSERT INTO Model (name) VALUES ("Gretchin");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Squad", "2018", "Gold", 3, 3, 29);
INSERT INTO Participant (fname, lname) VALUES ("Freddie", "Lifton");
INSERT INTO Model (name) VALUES ("Poxshambler");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Youngbloods", "2018", "Gold", 4, 4, 29);
INSERT INTO Participant (fname, lname) VALUES ("Stefan", "Johnsson");
INSERT INTO Model (name) VALUES ("Gellerpox Infected – Nightmare Hulk");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Gold", 5, 5, 29);
INSERT INTO Participant (fname, lname) VALUES ("Lewis", "Collins");
INSERT INTO Model (name) VALUES ("Killa Kan");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Vehicle", "2018", "Gold", 6, 6, 29);
INSERT INTO Participant (fname, lname) VALUES ("Michael", "Boonk");
INSERT INTO Model (name) VALUES ("Dark Angels Redempter");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Vehicle", "2018", "Bronze", 7, 7, 29);
INSERT INTO Participant (fname, lname) VALUES ("Mark", "Lifton");
INSERT INTO Model (name) VALUES ("Chaos Renegade vs Kabalite");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2018", "Silver", 8, 8, 29);
INSERT INTO Participant (fname, lname) VALUES ("Adie", "Bay");
INSERT INTO Model (name) VALUES ("Magnus the Ogryn");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Unbound", "2018", "Gold", 9, 9, 29);
INSERT INTO Model (name) VALUES ("Wulfen Fury");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2018", "Gold", 9, 9, 29);
INSERT INTO Participant (fname, lname) VALUES ("Edgar", "Ramos");
INSERT INTO Model (name) VALUES ("Deamon Prince");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Gold", 10, 10, 38);
INSERT INTO Participant (fname, lname) VALUES ("Richard", "Gray");
INSERT INTO Model (name) VALUES ("Fulgrim the Phoenician");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Silver", 11, 11, 38);
INSERT INTO Participant (fname, lname) VALUES ("David", "Soper");
INSERT INTO Model (name) VALUES ("Death Guard Terminator");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Bronze", 12, 12, 38);
INSERT INTO Participant (fname, lname) VALUES ("Matt", "Schuchman");
INSERT INTO Model (name) VALUES ("Cadian Master of Ordnance");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Squad", "2018", "Gold", 13, 13, 38);
INSERT INTO Participant (fname, lname) VALUES ("Paul", "Norton");
INSERT INTO Model (name) VALUES ("Necron Triarch Praetorian");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Silver", 14, 14, 38);
INSERT INTO Participant (fname, lname) VALUES ("Darren", "Latham");
INSERT INTO Model (name) VALUES ("Imperial Knight");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Vehicle", "2018", "Gold", 15, 15, 38);
INSERT INTO Participant (fname, lname) VALUES ("Andy", "Wardle");
INSERT INTO Model (name) VALUES ("Armiger Helverin");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Vehicle", "2018", "Silver", 16, 16, 38);
INSERT INTO Participant (fname, lname) VALUES ("John", "Simmons");
INSERT INTO Model (name) VALUES ("Tau Battlesuit Commander");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Gold", 17, 17, 38);
INSERT INTO Model (name) VALUES ("Magnus the Red");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Silver", 11, 11, 38);
INSERT INTO Participant (fname, lname) VALUES ("Louis", "Hunter");
INSERT INTO Model (name) VALUES ("Ork Weirdboy");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Bronze", 18, 18, 38);
INSERT INTO Model (name) VALUES ("Fir Bolg Standard Bearer");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2018", "Gold", 11, 11, 38);
INSERT INTO Participant (fname, lname) VALUES ("Tom", "Walton");
INSERT INTO Model (name) VALUES ("The Glottkin");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2018", "Silver", 19, 19, 38);
INSERT INTO Model (name) VALUES ("Ork Warboss");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Duel", "2018", "Bronze", 12, 12, 38);
INSERT INTO Participant (fname, lname) VALUES ("James", "Karch");
INSERT INTO Model (name) VALUES ("Abaddon the Despoiler");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Gold", 20, 20, 38);
INSERT INTO Model (name) VALUES ("Knight Crusader");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Vehicle", "2018", "Silver", 11, 11, 38);
INSERT INTO Model (name) VALUES ("Eversor Assassin");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Bronze", 12, 12, 38);
INSERT INTO Model (name) VALUES ("Adeptus Custodes Jetbike");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Gold", 11, 11, 38);
INSERT INTO Model (name) VALUES ("Imperial Knight Paladin");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Silver", 15, 15, 38);
INSERT INTO Model (name) VALUES ("Space Marine Dreadnought");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Vehicle", "2018", "Bronze", 19, 19, 38);
INSERT INTO Model (name) VALUES ("Chaos Renegade Sorcerer");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Gold", 12, 12, 38);
INSERT INTO Model (name) VALUES ("Lord of Contagion");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Large Model", "2018", "Silver", 11, 11, 38);
INSERT INTO Model (name) VALUES ("Dark Angels Space Marine");
INSERT INTO Medal (Category, Year, Award, mid, pid, eid) VALUES ("Warhammer 40000 Single Miniature", "2018", "Bronze", 12, 12, 38);
